# compareFiles.R
# Analyzes the rgroup.in, species.in, sxwprod_v2.in, and pxwphen.in files
# generated by rSFSTEP2.

################### Make an output directory #######################
system("mkdir output")

#####################################################################################
############################# Analyze RGroup files ##################################
#####################################################################################
system("mkdir output/rgroup_comparisons")

################## Locate all rgroup.in files ######################
rgroup.files <- list.files(".", pattern = "rgroup")

################### Remove the template file #######################
rgroup.files <- rgroup.files[!grepl(rgroup.files, pattern = "rgroup_template.in")]

all.group.parameters <- list()
resource.availibility <- list()
wet.dry.modifiers <- list()
wildfire <- list()

################ Loop through all rgroup.in files ##################
for(index in 1:length(rgroup.files)){
  ####################### Read an RGroup file ######################
  rgroup_data <- read.table(rgroup.files[index], fill = TRUE)
  
  # Line will keep track of our location in the file. This is necessary because R
  # cannot handle the "[end]" delimiter we use in STEPWAT files.
  line <- 1
  
  ##### Read the first table (all group parameters like space) #####
  all.group.parameters[[index]] <- list()
  while(rgroup_data[line,1] != "[end]"){
    this.line <- as.numeric(sapply(rgroup_data[line, 2:length(rgroup_data[line,])], as.character))
    all.group.parameters[[index]][[line]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
  last.end <- line  # Remember where we found the "[end]" delimiter
  
  ######### Read the second table (resource availibility) ##########
  resource.availibility[[index]] <- list()
  line <- line + 1
  while(rgroup_data[line,1] != "[end]"){
    this.line <- as.numeric(sapply(rgroup_data[line, 2:length(rgroup_data[line,])], as.character))
    resource.availibility[[index]][[line - last.end]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
  last.end <- line  # Remember where we found the "[end]" delimiter
  
  #### Read the third table (wet-dry modifiers for succulents) #####
  wet.dry.modifiers[[index]] <- list()
  line <- line + 1
  while(rgroup_data[line,1] != "[end]"){
    this.line <- as.numeric(sapply(rgroup_data[line, 2:length(rgroup_data[line,])], as.character))
    wet.dry.modifiers[[index]][[line - last.end]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
  last.end <- line  # Remember where we found the "[end]" delimiter
  
  # Read the fourth table (cheatgrass driven wildfire parameters) ##
  wildfire[[index]] <- list()
  line <- line + 1
  while(rgroup_data[line,1] != "[end]"){
    this.line <-  as.numeric(sapply(rgroup_data[line, ], as.character))
    wildfire[[index]][[line - last.end]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
}

####### Compress lists of lists of vectors into 3d arrays ##########
for(i in 1:length(resource.availibility)){
  resource.availibility[[i]] <- matrix(unlist(resource.availibility[[i]]), nrow = length(resource.availibility[[i]]), byrow = TRUE)
}
resource.availibility <- simplify2array(resource.availibility)

for(i in 1:length(all.group.parameters)){
  all.group.parameters[[i]] <- matrix(unlist(all.group.parameters[[i]]), nrow = length(all.group.parameters[[i]]), byrow = TRUE)
}
all.group.parameters <- simplify2array(all.group.parameters)

for(i in 1:length(wet.dry.modifiers)){
  wet.dry.modifiers[[i]] <- matrix(unlist(wet.dry.modifiers[[i]]), nrow = length(wet.dry.modifiers[[i]]), byrow = TRUE)
}
wet.dry.modifiers <- simplify2array(wet.dry.modifiers)

############## Convert wildfire to a 2d matrix #####################
wildfire <- matrix(unlist(wildfire), nrow = length(wildfire), byrow = TRUE)

############## Prepare all group parameters output #################
all.group.stats <- array(dim = c(length(all.group.parameters[ , 1, 1]), length(all.group.parameters[1, , 1]) * 3))
colnames(all.group.stats) <- rep(c("minimum", "maximum", "std"), length(all.group.parameters[1, , 1]))
for(row in 1:length(all.group.parameters[ , 1, 1])){
  for(col in 1:length(all.group.parameters[1, , 1])){
    all.group.stats[row, col * 3 - 2] <- round(min(all.group.parameters[row, col, ]), 5)
    all.group.stats[row, col * 3 - 1] <- round(max(all.group.parameters[row, col, ]), 5)
    all.group.stats[row, col * 3] <- round(sd(all.group.parameters[row, col, ]), 5)
  }
}

############### Prepare resource availibility output ###############
resource.availibility.stats <- array(dim = c(length(resource.availibility[ , 1, 1]), length(resource.availibility[1, , 1]) * 3))
colnames(resource.availibility.stats) <- rep(c("minimum", "maximum", "std"), length(resource.availibility[1, , 1]))
for(row in 1:length(resource.availibility[ , 1, 1])){
  for(col in 1:length(resource.availibility[1, , 1])){
    resource.availibility.stats[row, col * 3 - 2] <- round(min(resource.availibility[row, col, ]), 5)
    resource.availibility.stats[row, col * 3 - 1] <- round(max(resource.availibility[row, col, ]), 5)
    resource.availibility.stats[row, col * 3] <- round(sd(resource.availibility[row, col, ]), 5)
  }
}

############### Prepare wet-dry parameters output ##################
wet.dry.stats <- array(dim = c(length(wet.dry.modifiers[ , 1, 1]), length(wet.dry.modifiers[1, , 1]) * 3))
colnames(wet.dry.stats) <- rep(c("minimum", "maximum", "std"), length(wet.dry.modifiers[1, , 1]))
for(row in 1:length(wet.dry.modifiers[ , 1, 1])){
  for(col in 1:length(wet.dry.modifiers[1, , 1])){
    wet.dry.stats[row, col * 3 - 2] <- round(min(wet.dry.modifiers[row, col, ]), 5)
    wet.dry.stats[row, col * 3 - 1] <- round(max(wet.dry.modifiers[row, col, ]), 5)
    wet.dry.stats[row, col * 3] <- round(sd(wet.dry.modifiers[row, col, ]), 5)
  }
}

################### Prepare wildfire output ########################
wildfire.stats <- array(dim = c(1, ncol(wildfire) * 3))
colnames(wildfire.stats) <- rep(c("minimum", "maximum", "std"), ncol(wildfire))
for(col in 1:ncol(wildfire)){
  wildfire.stats[1, col * 3 - 2] <- round(min(wildfire[ , col]), 5)
  wildfire.stats[1, col * 3 - 1] <- round(max(wildfire[ , col]), 5)
  wildfire.stats[1, col * 3] <- round(sd(wildfire[ , col]), 5)
}

###################### Write output files ##########################
write.csv(all.group.stats, "output/rgroup_comparisons/all_group_parameters.csv")
write.csv(resource.availibility.stats, "output/rgroup_comparisonsresource_availibility_parameters.csv")
write.csv(wet.dry.stats, "output/rgroup_comparisons/wet_dry_parameters.csv")
write.csv(wildfire.stats, "output/rgroup_comparisons/wildfire_parameters.csv")

####################################################################################
########################### Compare swxphen.in files ###############################
####################################################################################
system("mkdir output/sxwphen_comparisons")

####################### Locate the files ###########################
phen.files <- list.files(".", pattern = "sxwphen")

##################### Store the original CSV #######################
phen.original <- read.csv("../../inputs/InputData_Phenology.csv", row.names = 1)

phen.data <- list()

###### Read the input files from the STEPWAT_DIST directory ########
for(index in 1:length(phen.files)){
  phen.data[[index]] <- read.table(phen.files[index], row.names = 1)
}

################# Convert the list to a 3d array ###################
for(i in 1:length(phen.data)){
  phen.data[[i]] <- data.matrix(phen.data[[i]])
}
phen.data <- simplify2array(phen.data)

###################### Write the CSV files #########################
for(file in 1:length(phen.files)){
  write.csv(round(phen.data[, , file] - phen.original, 7), paste0("output/sxwphen_comparisons/", phen.files[file], "-original.csv"))
}

####################################################################################
########################## Compare sxwprod_v2.in files #############################
####################################################################################
system("mkdir output/sxwprod_comparisons")

########## Locate the sxwprod files that were generated ############
prod.files <- list.files(".", pattern = "sxwprod")

############## Read the original input CSV files ###################
litter.original <- read.csv("../../inputs/InputData_Litter.csv", row.names = 1)
biomass.original <- read.csv("../../inputs/InputData_Biomass.csv", row.names = 1)
pctlive.original <- read.csv("../../inputs/InputData_PctLive.csv", row.names = 1)

litter <- c()
biomass.input <- c()
pctlive.input <- c()

################ Loop through the generated files ##################
for(index in 1:length(prod.files)){
  prod.data <- read.table(prod.files[index], fill = TRUE)
  
  ################### Parse the LITTER table #######################
  line <- 1
  last.end <- 0
  while(prod.data[line, 1] != "[end]"){
    litter[line] <- as.numeric(as.character(prod.data[line, 1]))
    line <- line + 1
  }
  last.end <- line
  line <- line + 1
  
  ################### Parse the BIOMASS table ######################
  while(prod.data[line, 1] != "[end]"){
    biomass.input[line - last.end] <- as.character(prod.data[line, 1])
    line <- line + 1
  }
  last.end <- line
  line <- line + 1
  
  ################### Parse the PCTLIVE table ######################
  while(prod.data[line, 1] != "[end]"){
    pctlive.input[line - last.end] <- as.character(prod.data[line, 1])
    line <- line + 1
  }
  
  ### R tead the tables matrices with 1 column, here we fix that ###
  pctlive.input <- matrix(pctlive.input, ncol = 13, byrow = TRUE)
  biomass.input <- matrix(biomass.input, ncol = 13, byrow = TRUE)
  rownames(pctlive.input) <- pctlive.input[ , 1]
  rownames(biomass.input) <- biomass.input[ , 1]
  pctlive.input <- pctlive.input[ , 2:ncol(pctlive.input)]
  biomass.input <- biomass.input[ , 2:ncol(biomass.input)]
  
  ########### Convert *.input from characters to numerics ##########
  pctlive <- matrix(nrow = nrow(pctlive.input), ncol = ncol(pctlive.input))
  biomass <- matrix(nrow = nrow(biomass.input), ncol = ncol(biomass.input))
  pctlive[,] <- as.numeric(pctlive.input[,])
  biomass[,] <- as.numeric(biomass.input[,])
  rownames(biomass) <- rownames(biomass.input)
  rownames(pctlive) <- rownames(pctlive.input)
  
  ##################### Write the CSV files ########################
  write.csv(pctlive - pctlive.original, paste0("output/sxwprod_comparisons/PCTLIVE.", prod.files[index], "-original.csv"))
  write.csv(biomass - biomass.original, paste0("output/sxwprod_comparisons/BIOMASS.", prod.files[index], "-original.csv"))
  write.csv(litter - litter.original, paste0("output/sxwprod_comparisons/LITTER.", prod.files[index], "-original.csv"))
}