# compareFiles.R
# Analyzes the rgroup.in, species.in, sxwprod_v2.in, and pxwphen.in files
# generated by rSFSTEP2.

# Security measure:
# Prevent this program from running outside of the DIST directory ##
stopifnot(endsWith(getwd(), "STEPWAT_DIST"))

################### Make an output directory #######################
if(!file.exists("output")){
  system("mkdir output")
}

#####################################################################################
############################# Analyze RGroup files ##################################
#####################################################################################
if(!file.exists("output/rgroup_comparisons")){
  system("mkdir output/rgroup_comparisons")
}

################## Locate all rgroup.in files ######################
rgroup.files <- list.files(".", pattern = "rgroup")

################### Remove the template file #######################
rgroup.files <- rgroup.files[!grepl(rgroup.files, pattern = "rgroup_template.in")]

all.group.parameters <- list()
resource.availibility <- list()
wet.dry.modifiers <- list()
wildfire <- list()

################ Loop through all rgroup.in files ##################
for(index in 1:length(rgroup.files)){
  ####################### Read an RGroup file ######################
  rgroup_data <- read.table(rgroup.files[index], fill = TRUE)
  
  # Line will keep track of our location in the file. This is necessary because R
  # cannot handle the "[end]" delimiter we use in STEPWAT files.
  line <- 1
  
  ##### Read the first table (all group parameters like space) #####
  all.group.parameters[[index]] <- list()
  while(rgroup_data[line,1] != "[end]"){
    this.line <- as.numeric(sapply(rgroup_data[line, 2:length(rgroup_data[line,])], 
                                   as.character))
    all.group.parameters[[index]][[line]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
  last.end <- line  # Remember where we found the "[end]" delimiter
  
  ######### Read the second table (resource availibility) ##########
  resource.availibility[[index]] <- list()
  line <- line + 1
  while(rgroup_data[line,1] != "[end]"){
    this.line <- as.numeric(sapply(rgroup_data[line, 2:length(rgroup_data[line,])], 
                                   as.character))
    resource.availibility[[index]][[line - last.end]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
  last.end <- line  # Remember where we found the "[end]" delimiter
  
  #### Read the third table (wet-dry modifiers for succulents) #####
  wet.dry.modifiers[[index]] <- list()
  line <- line + 1
  while(rgroup_data[line,1] != "[end]"){
    this.line <- as.numeric(sapply(rgroup_data[line, 2:length(rgroup_data[line,])], 
                                   as.character))
    wet.dry.modifiers[[index]][[line - last.end]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
  last.end <- line  # Remember where we found the "[end]" delimiter
  
  # Read the fourth table (cheatgrass driven wildfire parameters) ##
  wildfire[[index]] <- list()
  line <- line + 1
  while(rgroup_data[line,1] != "[end]"){
    this.line <-  as.numeric(sapply(rgroup_data[line, ], as.character))
    wildfire[[index]][[line - last.end]] <- this.line[!is.na(this.line)]
    line <- line + 1
  }
}

####### Compress lists of lists of vectors into 3d arrays ##########
for(i in 1:length(resource.availibility)){
  resource.availibility[[i]] <- matrix(unlist(resource.availibility[[i]]), 
                                       nrow = length(resource.availibility[[i]]), 
                                       byrow = TRUE)
}
resource.availibility <- simplify2array(resource.availibility)

for(i in 1:length(all.group.parameters)){
  all.group.parameters[[i]] <- matrix(unlist(all.group.parameters[[i]]), 
                                      nrow = length(all.group.parameters[[i]]), 
                                      byrow = TRUE)
}
all.group.parameters <- simplify2array(all.group.parameters)

for(i in 1:length(wet.dry.modifiers)){
  wet.dry.modifiers[[i]] <- matrix(unlist(wet.dry.modifiers[[i]]), 
                                   nrow = length(wet.dry.modifiers[[i]]), 
                                   byrow = TRUE)
}
wet.dry.modifiers <- simplify2array(wet.dry.modifiers)

############## Convert wildfire to a 2d matrix #####################
wildfire <- matrix(unlist(wildfire), nrow = length(wildfire), byrow = TRUE)

############## Prepare all group parameters output #################
all.group.stats <- array(dim = c(length(all.group.parameters[ , 1, 1]), 
                                 length(all.group.parameters[1, , 1]) * 3))
colnames(all.group.stats) <- rep(c("minimum", "maximum", "std"), 
                                 length(all.group.parameters[1, , 1]))
for(row in 1:length(all.group.parameters[ , 1, 1])){
  for(col in 1:length(all.group.parameters[1, , 1])){
    all.group.stats[row, col * 3 - 2] <- round(min(all.group.parameters[row, col, ]), 5)
    all.group.stats[row, col * 3 - 1] <- round(max(all.group.parameters[row, col, ]), 5)
    all.group.stats[row, col * 3] <- round(sd(all.group.parameters[row, col, ]), 5)
  }
}

############### Prepare resource availibility output ###############
resource.availibility.stats <- array(dim = c(length(resource.availibility[ , 1, 1]), 
                                             length(resource.availibility[1, , 1]) * 3))
colnames(resource.availibility.stats) <- rep(c("minimum", "maximum", "std"), 
                                             length(resource.availibility[1, , 1]))
for(row in 1:length(resource.availibility[ , 1, 1])){
  for(col in 1:length(resource.availibility[1, , 1])){
    resource.availibility.stats[row, col * 3 - 2] <- round(min(resource.availibility[row, col, ]), 5)
    resource.availibility.stats[row, col * 3 - 1] <- round(max(resource.availibility[row, col, ]), 5)
    resource.availibility.stats[row, col * 3] <- round(sd(resource.availibility[row, col, ]), 5)
  }
}

############### Prepare wet-dry parameters output ##################
wet.dry.stats <- array(dim = c(length(wet.dry.modifiers[ , 1, 1]), 
                               length(wet.dry.modifiers[1, , 1]) * 3))
colnames(wet.dry.stats) <- rep(c("minimum", "maximum", "std"), 
                               length(wet.dry.modifiers[1, , 1]))
for(row in 1:length(wet.dry.modifiers[ , 1, 1])){
  for(col in 1:length(wet.dry.modifiers[1, , 1])){
    wet.dry.stats[row, col * 3 - 2] <- round(min(wet.dry.modifiers[row, col, ]), 5)
    wet.dry.stats[row, col * 3 - 1] <- round(max(wet.dry.modifiers[row, col, ]), 5)
    wet.dry.stats[row, col * 3] <- round(sd(wet.dry.modifiers[row, col, ]), 5)
  }
}

################### Prepare wildfire output ########################
wildfire.stats <- array(dim = c(1, ncol(wildfire) * 3))
colnames(wildfire.stats) <- rep(c("minimum", "maximum", "std"), ncol(wildfire))
for(col in 1:ncol(wildfire)){
  wildfire.stats[1, col * 3 - 2] <- round(min(wildfire[ , col]), 5)
  wildfire.stats[1, col * 3 - 1] <- round(max(wildfire[ , col]), 5)
  wildfire.stats[1, col * 3] <- round(sd(wildfire[ , col]), 5)
}

###################### Write output files ##########################
write.csv(all.group.stats, 
          "output/rgroup_comparisons/all_group_parameters.csv")
write.csv(resource.availibility.stats, 
          "output/rgroup_comparisons/resource_availibility_parameters.csv")
write.csv(wet.dry.stats, 
          "output/rgroup_comparisons/wet_dry_parameters.csv")
write.csv(wildfire.stats, 
          "output/rgroup_comparisons/wildfire_parameters.csv")

####################################################################################
########################### Compare swxphen.in files ###############################
####################################################################################
if(!file.exists("output/sxwphen_comparisons")){
  system("mkdir output/sxwphen_comparisons")
}

####################### Locate the files ###########################
phen.files <- list.files(".", pattern = "sxwphen")

##################### Store the original CSV #######################
phen.original <- read.csv("../../inputs/InputData_Phenology.csv", row.names = 1)

phen.data <- list()

###### Read the input files from the STEPWAT_DIST directory ########
for(index in 1:length(phen.files)){
  phen.data[[index]] <- read.table(phen.files[index], row.names = 1)
}

############## Convert the list to 2d and 3d arrays ################
# The 2d array represents the difference between the derived file 
# and the original (derived - original). It is used for printing.
# The 3d represents the derived values. It is used for graphing.
# The 3d array is easier to work with. The 2d is easier to print.
phen.data.2d <- matrix(nrow = nrow(phen.data[[1]]) * length(phen.files),
                       ncol = 13)
phen.data.2d[, 1] <- rep(phen.files, each = nrow(phen.original))
rownames(phen.data.2d) <- rep(row.names(phen.original),
                              length(phen.files))
colnames(phen.data.2d) <- c("File Name", month.abb)
for(i in 1:length(phen.data)){
  phen.data[[i]] <- data.matrix(phen.data[[i]])
  phen.data.2d[(nrow(phen.original)*(i-1)+1):(i*nrow(phen.original)),2:13] <- data.matrix(phen.data[[i]] - phen.original)
}
phen.data <- simplify2array(phen.data)

####################### Create Graphics ############################
if(!file.exists("output/sxwphen_comparisons/graphics")){
  system("mkdir output/sxwphen_comparisons/graphics")
}

colors <- c("blue", "black", "red", 
            "green", "orange", "green4", 
            "brown", "purple", "aquamarine", 
            "pink", "grey")

for(rgroup in 1:length(phen.original[, 1])){
  for(startFile in seq(from = 1, to = length(phen.files), by = 10)){
    nextColor <- 2
    png(paste0("output/sxwphen_comparisons/graphics/", 
               row.names(phen.original)[rgroup], "_", 
               startFile, "-", min(length(phen.data[1,1,]), startFile + 9),
               "_graph.png"), 
        width = 1080, height = 720)
    plot(x = c(1:12), y = t(phen.original[rgroup,]), xlab = "Month", 
         ylab = "Phenological Activity", 
         main = paste0(row.names(phen.original)[rgroup], 
                       " Phenological Differences"),
         col = colors[1], type = "l", ylim = c(0, .5), lwd = 2)
    
    for(file in startFile:min(length(phen.data[1,1,]), startFile + 9)){
      points(x = c(1:12), 
             y = t(phen.data[rgroup, , file]), 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4) # 3 and 4 fit well in a 1080 image
      nextColor <- nextColor + 1
    }
    
    legend("topleft",
           phen.files[startFile:min(length(phen.data[1,1,]), startFile + 9)],
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    dev.off()
  }
}

###################### Write the CSV file ##########################
write.csv(phen.data.2d, 
          paste0("output/sxwphen_comparisons/", 
                 "Derived_Files-Original.csv"))

####################################################################################
########################## Compare sxwprod_v2.in files #############################
####################################################################################
if(!file.exists("output/sxwprod_comparisons")){
  system("mkdir output/sxwprod_comparisons")
}

########## Locate the sxwprod files that were generated ############
prod.files <- list.files(".", pattern = "sxwprod")

############## Read the original input CSV files ###################
litter.original <- read.csv("../../inputs/InputData_Litter.csv", row.names = 1)
biomass.original <- read.csv("../../inputs/InputData_Biomass.csv", row.names = 1)
pctlive.original <- read.csv("../../inputs/InputData_PctLive.csv", row.names = 1)

litter <- c(); biomass.input <- c(); pctlive.input <- c()

litter.list <- list(); biomass.list <- list(); pctlive.list <- list()

################ Loop through the generated files ##################
for(index in 1:length(prod.files)){
  prod.data <- read.table(prod.files[index], fill = TRUE)
  
  ################### Parse the LITTER table #######################
  line <- 1
  last.end <- 0
  while(prod.data[line, 1] != "[end]"){
    litter[line] <- as.numeric(as.character(prod.data[line, 1]))
    line <- line + 1
  }
  last.end <- line
  line <- line + 1
  
  ################### Parse the BIOMASS table ######################
  while(prod.data[line, 1] != "[end]"){
    biomass.input[line - last.end] <- as.character(prod.data[line, 1])
    line <- line + 1
  }
  last.end <- line
  line <- line + 1
  
  ################### Parse the PCTLIVE table ######################
  while(prod.data[line, 1] != "[end]"){
    pctlive.input[line - last.end] <- as.character(prod.data[line, 1])
    line <- line + 1
  }
  
  ### R tead the tables matrices with 1 column, here we fix that ###
  pctlive.input <- matrix(pctlive.input, ncol = 13, byrow = TRUE)
  biomass.input <- matrix(biomass.input, ncol = 13, byrow = TRUE)
  rownames(pctlive.input) <- pctlive.input[ , 1]
  rownames(biomass.input) <- biomass.input[ , 1]
  pctlive.input <- pctlive.input[ , 2:ncol(pctlive.input)]
  biomass.input <- biomass.input[ , 2:ncol(biomass.input)]
  
  ########### Convert *.input from characters to numerics ##########
  pctlive <- matrix(nrow = nrow(pctlive.input), ncol = ncol(pctlive.input))
  biomass <- matrix(nrow = nrow(biomass.input), ncol = ncol(biomass.input))
  pctlive[,] <- as.numeric(pctlive.input[,])
  biomass[,] <- as.numeric(biomass.input[,])
  rownames(biomass) <- rownames(biomass.input)
  rownames(pctlive) <- rownames(pctlive.input)
  
  pctlive.list[[index]] <- pctlive
  biomass.list[[index]] <- biomass
  litter.list[[index]] <- litter
  
  ##################### Write the CSV files ########################
  write.csv(pctlive - pctlive.original, 
            paste0("output/sxwprod_comparisons/PCTLIVE.", 
                   prod.files[index], 
                   "-original.csv"))
  write.csv(biomass - biomass.original, 
            paste0("output/sxwprod_comparisons/BIOMASS.", 
                   prod.files[index], "-original.csv"))
  write.csv(litter - litter.original, 
            paste0("output/sxwprod_comparisons/LITTER.", 
                   prod.files[index], "-original.csv"))
}

#################### Create LITTER Graphics ########################
if(!file.exists("output/sxwprod_comparisons/LITTER_graphics")){
  system("mkdir output/sxwprod_comparisons/LITTER_graphics")
}

for(startFile in seq(from = 1, to = length(prod.files), by = 10)){
  nextColor <- 2
  png(paste0("output/sxwprod_comparisons/LITTER_graphics/", 
             "LITTER_", startFile, "-", 
             min(length(litter.list), startFile + 9),
             "_graph.png"), 
      width = 1080, height = 720)
  plot(x = c(1:12), y = t(litter.original), xlab = "Month", 
       ylab = "LITTER", 
       main = "LITTER Differences",
       col = colors[1], type = "l", ylim = c(0, 1), lwd = 2)
  
  for(file in startFile:min(length(litter.list), startFile + 9)){
    points(x = c(1:12), 
           y = litter.list[[file]], 
           col = colors[nextColor], 
           pch = (nextColor-1), 
           cex = 3, lwd = 4)
    nextColor <- nextColor + 1
  }
  
  legend("topright",
         prod.files[startFile:min(length(prod.files), startFile + 9)],
         col = colors[2:(nextColor-1)],
         pch = 1:(nextColor-2))
  
  dev.off()
}

#################### Create BIOMASS Graphics #######################
if(!file.exists("output/sxwprod_comparisons/biomass_graphics")){
  system("mkdir output/sxwprod_comparisons/biomass_graphics")
}

for(rgroup in 1:nrow(biomass.original)){
  for(startFile in seq(from = 1, to = length(prod.files), by = 10)){
    nextColor <- 2
    png(paste0("output/sxwprod_comparisons/biomass_graphics/", 
               row.names(biomass.original)[rgroup], 
               "_", startFile, "-", 
               min(length(prod.files), startFile + 9),
               "_biomass_graph.png"), 
        width = 1080, height = 720)
    
    plot(x = c(1:12), y = t(biomass.original[rgroup, ]), xlab = "Month", 
         ylab = "Biomass value", 
         main = paste0(row.names(biomass.original)[rgroup],
                       " Biomass Differences"),
         col = colors[1], type = "l", ylim = c(0, 1), lwd = 2)
    
    for(file in startFile:min(length(prod.files), startFile + 9)){
      points(x = c(1:12), 
             y = biomass.list[[file]][rgroup, ], 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4)
      nextColor <- nextColor + 1
    }
    
    legend("topright",
           prod.files[startFile:min(length(prod.files), startFile + 9)],
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    dev.off()
  }
}

#################### Create PCTLIVE Graphics #######################
if(!file.exists("output/sxwprod_comparisons/pctlive_graphics")){
  system("mkdir output/sxwprod_comparisons/pctlive_graphics")
}

for(rgroup in 1:nrow(pctlive.original)){
  for(startFile in seq(from = 1, to = length(prod.files), by = 10)){
    nextColor <- 2
    png(paste0("output/sxwprod_comparisons/pctlive_graphics/", 
               row.names(pctlive.original)[rgroup], "_",
               startFile, "-", 
               min(length(prod.files), startFile + 9),
               "_pctlive_graph.png"), 
        width = 1080, height = 720)
    
    plot(x = c(1:12), y = t(pctlive.original[rgroup, ]), xlab = "Month", 
         ylab = "% Live Value", 
         main = paste0(row.names(pctlive.original)[rgroup],
                       " % Live Differences"),
         col = colors[1], type = "l", ylim = c(0, 1), lwd = 2)
    
    for(file in startFile:min(length(prod.files), startFile + 9)){
      points(x = c(1:12), 
             y = pctlive.list[[file]][rgroup, ], 
             col = colors[nextColor], 
             pch = (nextColor-1), 
             cex = 3, lwd = 4)
      nextColor <- nextColor + 1
    }
    
    legend("topright",
           prod.files[startFile:min(length(prod.files), startFile + 9)],
           col = colors[2:(nextColor-1)],
           pch = 1:(nextColor-2))
    
    dev.off()
  }
}
